### ISSUE TITLE
Recent Pull request didn't fix "not a module" issue

### ISSUE THREAD

**Issue by tenowg** [inversify/InversifyJS#35]
My recent #32 pull request failed for fix the issue that I was attempting to fix. It seems that you can't use

```
declare module 'inversify'
```

inside the .d.ts used by the typings declared in package.json, which was the reason for the extra inversify-node.d.ts
![notamodule](https://cloud.githubusercontent.com/assets/1147426/12315550/3be95daa-ba4a-11e5-8354-cbd89e76bb8d.PNG)

the typings declared in package.json should remove the need to use /// <reference calls.

**Comment by Jameskmonger** [comment]
Why do you not want to use /// <reference> calls to the typings file?

**Comment by tenowg** [comment]
Well, simply because if there is a way to prevent it, and not clutter code more by have essentially 2 import statements, I am all for it. Also less steps to setup... either moving the files to a typings folder for a shorter reference, or typing long reference paths, when all that is needed is a single `import {Kernel} from 'inversify'` and the rest is handled by tsc and resolveModules. I had it working, albet it needed some tweaking and fixing to be clean, but that was reversed... oh well.

**Comment by remojansen** [comment]
Hi guys, I was trying to add node and browser (global) examples and I saw this issue as well. I'm at work but I will look at it when I get home. I would like to add some unit tests or integration test to ensure that we don't have this issues again. Yesterday I merged code to master that is not fully working and we need to avoid that as much as possible.

It is being painful to get this working but we need to do it :) as @tenowg said is more convenient and it the recommended way to distribute type definition files since TypeScript 1.5.

**Comment by tenowg** [comment]
@remojansen I do still have the repo up (look at #32) that has a working example of it working globally, with import {} and import as... it is convoluted, but it does show that it can be done, I really don't know how to clean it up from there tho...

**Comment by Jameskmonger** [comment]
Not too sure about the maintainability of this solution... There are multiple files to maintain this way

**Comment by tenowg** [comment]
actually, the way I have it setup (not perfect by any means) only requires one file to be maintained, inversify.d.ts

**Comment by remojansen** [comment]
I'm going to close this issue to ensure that we only have one unique issue to refer to this problem. You can follow the updates at #46
